name: GitHub

on:
  push:
    branches:
      - master

  # schedule:
  #   - cron: '0 8,12,16,20 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "w@zce.me"
          git config --local user.name "zce"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "bot commit every day"
          git push
