name: NPM

on:
  push:
    branches:
      - master

  schedule:
    - cron:  '*/5 * * * *'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: npm install caz
      - run: npm install caz -g
