name: NPM

on:
  push:
    branches:
      - master

  schedule:
    - cron:  '* * * * *'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./install
